version: '3.8'

networks:
  web:
    ipam:
      config:
        - subnet: 173.28.10.0/29

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front-end_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ./:/app:cached
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    networks:
      web:
        ipv4_address: 173.28.10.2
        #api:
        # build: ./api
        # container_name: api_c
        # ports: 
        # - '4000:4000'
        # volumes:
        #  - ./api:/app
        #  - ./app/node_modules
